// Product data parsed from CSV
export const productData = [
  {
    product_id: 2000,
    product_name: "Wireless Earbuds",
    description: "Latest tech with smart features and efficient battery life.",
    category: "Electronics",
    origin_country: "China",
    weight_kg: 0.15,
    packaging: "Recycled",
    delivery_method: "Sea",
    delivery_distance_km: 7707,
    delivery_speed: "Express",
    price_usd: 93.47,
    image_url: "https://m.media-amazon.com/images/I/71ndbdVgC7L._AC_UY436_FMwebp_QL65_.jpg"
  },
  {
    product_id: 2001,
    product_name: "Smart Watch",
    description: "Latest tech with smart features and efficient battery life.",
    category: "Electronics",
    origin_country: "India",
    weight_kg: 0.59,
    packaging: "Cardboard",
    delivery_method: "Air",
    delivery_distance_km: 7830,
    delivery_speed: "Standard",
    price_usd: 105.29,
    image_url: "https://m.media-amazon.com/images/I/61fxl+1+kZL._AC_UY436_FMwebp_QL65_.jpg"
  },
  {
    product_id: 2002,
    product_name: "Bluetooth Speaker",
    description: "Latest tech with smart features and efficient battery life.",
    category: "Electronics",
    origin_country: "USA",
    weight_kg: 3.24,
    packaging: "Recycled",
    delivery_method: "Sea",
    delivery_distance_km: 2218,
    delivery_speed: "Standard",
    price_usd: 119.21,
    image_url: "https://m.media-amazon.com/images/I/71NTrD1tqAL._AC_UY436_FMwebp_QL65_.jpg"
  },
  {
    product_id: 2003,
    product_name: "Portable Charger",
    description: "Latest tech with smart features and efficient battery life.",
    category: "Electronics",
    origin_country: "China",
    weight_kg: 1.76,
    packaging: "Cardboard",
    delivery_method: "Sea",
    delivery_distance_km: 7864,
    delivery_speed: "Express",
    price_usd: 74.66,
    image_url: "https://m.media-amazon.com/images/I/51mFLvYqKlL._AC_UY436_FMwebp_QL65_.jpg"
  },
  {
    product_id: 2004,
    product_name: "Noise Cancelling Headphones",
    description: "Latest tech with smart features and efficient battery life.",
    category: "Electronics",
    origin_country: "China",
    weight_kg: 0.34,
    packaging: "Recycled",
    delivery_method: "Road",
    delivery_distance_km: 4510,
    delivery_speed: "Express",
    price_usd: 142.32,
    image_url: "https://m.media-amazon.com/images/I/610DB8Cwm7L._AC_UY436_FMwebp_QL65_.jpg"
  },
  {
    product_id: 2005,
    product_name: "Air Purifier",
    description: "Compact and energy-efficient design for everyday use.",
    category: "Home Appliances",
    origin_country: "Vietnam",
    weight_kg: 12.49,
    packaging: "Cardboard",
    delivery_method: "Air",
    delivery_distance_km: 359,
    delivery_speed: "Express",
    price_usd: 108.74,
    image_url: "https://m.media-amazon.com/images/I/61jwM+adjXL._SX679_.jpg"
  },
  {
    product_id: 2006,
    product_name: "Electric Kettle",
    description: "Compact and energy-efficient design for everyday use.",
    category: "Home Appliances",
    origin_country: "Germany",
    weight_kg: 1.87,
    packaging: "Cardboard",
    delivery_method: "Road",
    delivery_distance_km: 5047,
    delivery_speed: "Express",
    price_usd: 105.05,
    image_url: "https://m.media-amazon.com/images/I/71Tck+rJ2SL._AC_UY436_FMwebp_QL65_.jpg"
  },
  {
    product_id: 2007,
    product_name: "Induction Cooktop",
    description: "Compact and energy-efficient design for everyday use.",
    category: "Home Appliances",
    origin_country: "India",
    weight_kg: 4.36,
    packaging: "Cardboard",
    delivery_method: "Sea",
    delivery_distance_km: 6121,
    delivery_speed: "Express",
    price_usd: 272.12,
    image_url: "https://m.media-amazon.com/images/I/715L3WOq4JL._AC_UY436_FMwebp_QL65_.jpg"
  },
  {
    product_id: 2008,
    product_name: "Vacuum Cleaner",
    description: "Compact and energy-efficient design for everyday use.",
    category: "Home Appliances",
    origin_country: "Germany",
    weight_kg: 10.97,
    packaging: "Cardboard",
    delivery_method: "Air",
    delivery_distance_km: 7800,
    delivery_speed: "Standard",
    price_usd: 49.85,
    image_url: "https://m.media-amazon.com/images/I/61nsOzbC4BL._AC_UY436_FMwebp_QL65_.jpg"
  },
  {
    product_id: 2009,
    product_name: "Mini Refrigerator",
    description: "Compact and energy-efficient design for everyday use.",
    category: "Home Appliances",
    origin_country: "Vietnam",
    weight_kg: 22.83,
    packaging: "Cardboard",
    delivery_method: "Air",
    delivery_distance_km: 4954,
    delivery_speed: "Express",
    price_usd: 145.7,
    image_url: "https://m.media-amazon.com/images/I/71R5O4sE3WL._AC_UY436_FMwebp_QL65_.jpg"
  },
  {
    product_id: 2010,
    product_name: "Men's Cotton T-Shirt",
    description: "Comfortable and stylish",
    category: "Clothing",
    origin_country: "Vietnam",
    weight_kg: 0.36,
    packaging: "Plastic",
    delivery_method: "Sea",
    delivery_distance_km: 8442,
    delivery_speed: "Standard",
    price_usd: 257.96,
    image_url: "https://m.media-amazon.com/images/I/81j27szi3cL._AC_UL640_FMwebp_QL65_.jpg"
  },
  {
    product_id: 2011,
    product_name: "Women's Hoodie",
    description: "Comfortable",
    category: "Clothing",
    origin_country: "USA",
    weight_kg: 1.86,
    packaging: "Cardboard",
    delivery_method: "Air",
    delivery_distance_km: 2191,
    delivery_speed: "Express",
    price_usd: 223.69,
    image_url: "https://m.media-amazon.com/images/I/71gjB+gLnQL._AC_UL640_FMwebp_QL65_.jpg"
  },
  {
    product_id: 2012,
    product_name: "Denim Jeans",
    description: "Comfortable",
    category: "Clothing",
    origin_country: "India",
    weight_kg: 1.53,
    packaging: "Plastic",
    delivery_method: "Air",
    delivery_distance_km: 3755,
    delivery_speed: "Standard",
    price_usd: 30.67,
    image_url: "https://m.media-amazon.com/images/I/61-r2kTvZDL._AC_UL640_FMwebp_QL65_.jpg"
  },
  {
    product_id: 2013,
    product_name: "Casual Sneakers",
    description: "Comfortable",
    category: "Clothing",
    origin_country: "Vietnam",
    weight_kg: 1.81,
    packaging: "Cardboard",
    delivery_method: "Sea",
    delivery_distance_km: 3479,
    delivery_speed: "Standard",
    price_usd: 189.73,
    image_url: "https://m.media-amazon.com/images/I/518nHJOJsLL._AC_UL640_FMwebp_QL65_.jpg"
  },
  {
    product_id: 2014,
    product_name: "Sports Jacket",
    description: "Comfortable",
    category: "Clothing",
    origin_country: "China",
    weight_kg: 1.67,
    packaging: "Recycled",
    delivery_method: "Air",
    delivery_distance_km: 8174,
    delivery_speed: "Express",
    price_usd: 65.98,
    image_url: "https://m.media-amazon.com/images/I/412O5U6TjaL._AC_UL640_FMwebp_QL65_.jpg"
  },
  {
    product_id: 2015,
    product_name: "Face Moisturizer",
    description: "Made from organic ingredients with recyclable packaging.",
    category: "Beauty",
    origin_country: "Vietnam",
    weight_kg: 0.26,
    packaging: "Plastic",
    delivery_method: "Road",
    delivery_distance_km: 684,
    delivery_speed: "Standard",
    price_usd: 195.65,
    image_url: "https://m.media-amazon.com/images/I/61SSD0FoULL._AC_UL640_FMwebp_QL65_.jpg"
  },
  {
    product_id: 2016,
    product_name: "Organic Shampoo",
    description: "Made from organic ingredients with recyclable packaging.",
    category: "Beauty",
    origin_country: "Vietnam",
    weight_kg: 0.42,
    packaging: "Recycled",
    delivery_method: "Air",
    delivery_distance_km: 7612,
    delivery_speed: "Standard",
    price_usd: 244.08,
    image_url: "https://m.media-amazon.com/images/I/619kXpHl4yL._AC_UL640_FMwebp_QL65_.jpg"
  },
  {
    product_id: 2017,
    product_name: "Lip Balm",
    description: "Made from organic ingredients with recyclable packaging.",
    category: "Beauty",
    origin_country: "Germany",
    weight_kg: 0.1,
    packaging: "Cardboard",
    delivery_method: "Sea",
    delivery_distance_km: 8219,
    delivery_speed: "Express",
    price_usd: 129.19,
    image_url: "https://m.media-amazon.com/images/I/61wdV4uPH-L._AC_UL640_FMwebp_QL65_.jpg"
  },
  {
    product_id: 2018,
    product_name: "Sunscreen Lotion",
    description: "Made from organic ingredients with recyclable packaging.",
    category: "Beauty",
    origin_country: "USA",
    weight_kg: 0.11,
    packaging: "Recycled",
    delivery_method: "Road",
    delivery_distance_km: 2299,
    delivery_speed: "Express",
    price_usd: 55.41,
    image_url: "https://m.media-amazon.com/images/I/614yLOLZEEL._AC_UL640_FMwebp_QL65_.jpg"
  },
  {
    product_id: 2019,
    product_name: "Aloe Vera Gel",
    description: "Made from organic ingredients with recyclable packaging.",
    category: "Beauty",
    origin_country: "India",
    weight_kg: 0.37,
    packaging: "Recycled",
    delivery_method: "Road",
    delivery_distance_km: 7796,
    delivery_speed: "Standard",
    price_usd: 107.66,
    image_url: "https://m.media-amazon.com/images/I/51NFtLbWPoL._AC_UL640_FMwebp_QL65_.jpg"
  },
  {
    product_id: 2020,
    product_name: "Fiction Novel",
    description: "Printed on eco-friendly paper with a sustainable mindset.",
    category: "Books",
    origin_country: "India",
    weight_kg: 0.24,
    packaging: "Recycled",
    delivery_method: "Road",
    delivery_distance_km: 9353,
    delivery_speed: "Standard",
    price_usd: 171.52,
    image_url: "https://m.media-amazon.com/images/I/61pZyTuNDYL._AC_UY436_FMwebp_QL65_.jpg"
  },
  {
    product_id: 2021,
    product_name: "Self Help Book",
    description: "Printed on eco-friendly paper with a sustainable mindset.",
    category: "Books",
    origin_country: "China",
    weight_kg: 0.38,
    packaging: "Recycled",
    delivery_method: "Air",
    delivery_distance_km: 1091,
    delivery_speed: "Standard",
    price_usd: 24.52,
    image_url: "https://m.media-amazon.com/images/I/712K3sdLlRL._AC_UY436_FMwebp_QL65_.jpg"
  },
  {
    product_id: 2022,
    product_name: "Science Textbook",
    description: "Printed on eco-friendly paper with a sustainable mindset.",
    category: "Books",
    origin_country: "India",
    weight_kg: 1.74,
    packaging: "Cardboard",
    delivery_method: "Air",
    delivery_distance_km: 1484,
    delivery_speed: "Express",
    price_usd: 276.71,
    image_url: "https://m.media-amazon.com/images/I/517W9NSMu+L._AC_UY436_FMwebp_QL65_.jpg"
  },
  {
    product_id: 2023,
    product_name: "Cookbook",
    description: "Printed on eco-friendly paper with a sustainable mindset.",
    category: "Books",
    origin_country: "China",
    weight_kg: 0.69,
    packaging: "Recycled",
    delivery_method: "Air",
    delivery_distance_km: 1262,
    delivery_speed: "Standard",
    price_usd: 245.79,
    image_url: "https://m.media-amazon.com/images/I/911pI+iDkCL._AC_UY436_FMwebp_QL65_.jpg"
  },
  {
    product_id: 2024,
    product_name: "Children's Story Book",
    description: "Printed on eco-friendly paper with a sustainable mindset.",
    category: "Books",
    origin_country: "Germany",
    weight_kg: 0.52,
    packaging: "Cardboard",
    delivery_method: "Sea",
    delivery_distance_km: 6137,
    delivery_speed: "Standard",
    price_usd: 116.22,
    image_url: "https://m.media-amazon.com/images/I/81WCSu2RoJS._AC_UY436_FMwebp_QL65_.jpg"
  }
];

export const getProductsByCategory = (category) => {
  if (!category || category === 'All') {
    return productData;
  }
  return productData.filter(product => product.category === category);
};

export const getProductById = (id) => {
  return productData.find(product => product.product_id === parseInt(id));
};

export const getUniqueCategories = () => {
  return [...new Set(productData.map(product => product.category))];
};
